_target_: ml_catalog.modules.GammaAssociator
crs:
  _target_: pyproj.crs.CRS.from_user_input
  value: "+proj=sterea +lon_0=12 +lat_0=46 +units=km +type=crs"
config:
  dims: ["x(km)", "y(km)", "z(km)"]
  use_dbscan: True
  use_amplitude: False
  x(km): [-300, 400]
  y(km): [-350, 250]
  z(km): [0, 40]
  vel:
    p: 5.85
    s: 3.28
  method: "BGMM"
  oversample_factor: 5
  dbscan_eps: 13.4 # seconds
  dbscan_min_samples: 3
  # Filtering
  min_picks_per_eq: 5
  min_p_picks_per_eq: 3
  min_s_picks_per_eq: 2
  covariance_prior_pre: [5.0, 5.0] # Andrea Carducci reference
  max_sigma11: 1.0
  #max_sigma22: 1.0
  #max_sigma12: 1.0