_target_: ml_catalog.modules.REALAssociator

p_picks: 3
s_picks: 3
total_picks: 6
p_and_s_picks: 3
max_residual_std: 0.5
min_p_to_s_separation: 0.5
event_separation_sec: 5

search_range_horizontal_deg: 0.1
search_range_vertical_km: 40
grid_size_horizontal_deg: 0.04
grid_size_vertical_km: 2
vp: 5.85
vs: 3.28
#shallow_vp: 5.3
#shallow_vs: 3.1
elevation_correction: False

use_model1d: False
#tt_db: "OGS/data/VelocityModel/1D/tt_db.txt"
#tt_range_horizontal_deg: 0.01
#tt_grid_size_horizontal_deg: 0.01
#tt_grid_size_vertical_km: 0.1
