_target_: OGS.src.ogsmagnitude.OGSLocalMagnitude
station_corrections:
  _target_: pandas.read_csv
  filepath_or_buffer: "OGS/data/Magnitude/LocalMagnitude/MagnitudeCorrection.csv"
ignore_stations:
  _target_: pandas.read_csv
  filepath_or_buffer: "OGS/data/Magnitude/LocalMagnitude/IGNORE_STATIONS.csv"