
compare_all:

compare_hpl:
	ogscompare.py -B /Users/admin/Desktop/OGS_Catalog/catalogs/OGSCatalog/.hpl -T /Users/admin/Desktop/OGS_Catalog/catalogs/OGS/ -S /Users/admin/Desktop/Monica/PhD/data/station -W /Volumes/Expansion/KEN/waveforms