parser:
	python ogsparser.py -v -f /Users/admin/Desktop/OGS_Catalog/OGS/data/manual/onlyEQ_NLL1D-2020* -o /Users/admin/Desktop/Monica/PhD/catalog/OGSCatalog --merge

download:
	python ogsdownloader.py -v -d /Volumes/Expansion/KEN/waveforms -D 20240320 20240620