"""
=============================================================================
OGS PUN File Parser - Hypo71 Event Summary Extractor
=============================================================================

OVERVIEW:
This module parses OGS .pun format files containing event-level summaries
generated by legacy Hypo71 location workflows. PUN files store one summary
record per event, including origin time, hypocenter, magnitude, and quality
metrics.

FILE FORMAT DESCRIPTION:
  The .pun format uses one fixed-width record per event with fields for:
  - Origin date/time (YYMMDDHHMM plus seconds)
  - Latitude and longitude in degree-minute notation
  - Depth and duration magnitude
  - Number of observations, GAP, DMIN, RMS, ERH, ERZ, and QM quality code
  - A leading header line that is skipped before parsing begins

KEY FEATURES:
  - Regex-based extraction with named capture groups
  - Date range filtering for temporal subsetting
  - Conversion of degree-minute coordinates to decimal degrees
  - Preservation of event quality metrics for downstream analysis
  - Parquet output via the shared OGSDataFile logging pipeline

USAGE:
  Command line:
    python ogspun.py -f input.pun -D 20240320 20240620 -v

  Programmatic:
    from ogspun import DataFilePUN
    parser = DataFilePUN(Path("input.pun"), start_date, end_date)
    parser.read()
    parser.log()

OUTPUT:
  - self.EVENTS: DataFrame with event origin, geometry, and quality metrics
  - self.events: Dict mapping dates to grouped event DataFrames

DEPENDENCIES:
  - pandas: DataFrame operations and Parquet I/O
  - obspy: UTCDateTime for seismological time handling
  - ogsconstants: OGS-specific constants and regex fragments
  - ogsdatafile: Base class providing regex extraction and logging helpers

=============================================================================
"""

# -----------------------------------------------------------------------------
# IMPORTS
# -----------------------------------------------------------------------------

# Standard library: command-line argument parsing
import argparse

# Standard library: filesystem path handling
from pathlib import Path

# ObsPy: seismological time conversions
from obspy import UTCDateTime

# Standard library: date/time objects and time deltas
from datetime import datetime, timedelta as td

# Pandas: tabular data manipulation
import pandas as pd

# Local module: OGS-specific constants and formatting strings
import ogsconstants as OGS_C

# Local module: OGS-specific argument parsing helpers
import ogsutils as OGS_U

# Local module: base parser for extraction and logging
from ogsdatafile import OGSDataFile

# -----------------------------------------------------------------------------
# CONSTANTS
# -----------------------------------------------------------------------------

# Base path for data files (two levels up from this script's location)
DATA_PATH = Path(__file__).parent.parent.parent


# =============================================================================
# ARGUMENT PARSER
# =============================================================================

def parse_arguments():
  """
  Parse command-line arguments for the PUN file processor.

  Returns:
    argparse.Namespace with:
      - file: List of Path objects to input .pun files
      - dates: Tuple of (start_date, end_date) for filtering
      - verbose: Boolean flag for debug output
  """
  parser = argparse.ArgumentParser(description="Run OGS PUN quality checks")

  # -f/--file: Input file path(s), required, accepts multiple files
  parser.add_argument(
    "-f", "--file", type=Path, required=True, nargs=OGS_C.ONE_MORECHAR_STR,
    help="Path to the input file")

  # -D/--dates: Date range filter, optional, format YYYYMMDD
  parser.add_argument(
    '-D', "--dates", required=False, metavar=OGS_C.DATE_STD,
    type=OGS_U.is_date, nargs=2, action=OGS_U.SortDatesAction,
    default=[datetime.strptime("20240320", OGS_C.YYYYMMDD_FMT),
             datetime.strptime("20240620", OGS_C.YYYYMMDD_FMT)],
    help="Specify the beginning and ending (inclusive) Gregorian date " \
         "(YYYYMMDD) range to work with.")

  # -v/--verbose: Enable detailed logging output
  parser.add_argument(
    '-v', "--verbose", action='store_true', default=False,
    help="Enable verbose output")

  return parser.parse_args()


# =============================================================================
# DataFilePUN Class - PUN Format Parser
# =============================================================================

class DataFilePUN(OGSDataFile):
  """
  Parser for OGS .pun format event summary files.

  Extends OGSDataFile to parse legacy Hypo71 event summary output. Each data
  line represents one event and includes origin time, hypocenter, and several
  quality-control metrics used by downstream catalog workflows.

  Attributes:
    RECORD_EXTRACTOR_LIST: Regex patterns for event summary lines
  """

  # -------------------------------------------------------------------------
  # RECORD EXTRACTOR: fixed-width event summary line
  # -------------------------------------------------------------------------
  RECORD_EXTRACTOR_LIST = [
    fr"^1(?P<{OGS_C.DATE_STR}>\d{{6}}[\s\d]\d[\s\d]\d)\s",  # Date [YYMMDDHHMM]
    fr"(?P<{OGS_C.SECONDS_STR}>[\s\d]\d\.\d{{2}})\s",       # Seconds [SS.ss]
    fr"(?P<{OGS_C.LATITUDE_STR}>[\s\d\-\.]{{8}})\s{{2}}",   # Latitude [DD-MM.mm]
    fr"(?P<{OGS_C.LONGITUDE_STR}>[\s\d\-\.]{{8}})\s{{2}}",  # Longitude [DD-MM.mm]
    fr"(?P<{OGS_C.DEPTH_STR}>[\s\d\-\.]{{5}})\s{{2}}",      # Depth
    fr"(?P<{OGS_C.MAGNITUDE_D_STR}>[\-\s\d\.]{{5}})",       # Duration Magnitude
    fr"(?P<{OGS_C.NO_STR}>[\s\d]{{3}})\s",                  # Number of Observations
    fr"(?P<{OGS_C.GAP_STR}>[\s\d]{{3}})",                   # GAP
    fr"(?P<{OGS_C.DMIN_STR}>[\s\d]{{2}}\d\.\d)",            # DMIN
    fr"(?P<{OGS_C.RMS_STR}>[\s\d]\d\.\d{{2}})",             # RMS
    fr"(?P<{OGS_C.ERH_STR}>([\s\d\.\-]{{5}}))",             # ERH
    fr"(?P<{OGS_C.ERZ_STR}>([\s\d\.\-]{{5}}))\s",           # ERZ
    fr"(?P<{OGS_C.QM_STR}>[A-Z][0-9])",                     # QM
  ]

  @staticmethod
  def _parse_seconds(value: str) -> td:
    """Convert the fixed-width seconds field into a timedelta."""
    return td(seconds=float(value))

  @staticmethod
  def _parse_origin_time(date_value: str, seconds: td) -> datetime:
    """Convert the origin date and seconds fields into a datetime."""
    return datetime.strptime(
      date_value.replace(OGS_C.SPACE_STR, OGS_C.ZERO_STR),
      OGS_C.DATETIME_FMT[:-2]) + seconds

  @staticmethod
  def _parse_coordinate(value: str):
    """Convert a degree-minute coordinate string to decimal degrees."""
    if not value:
      return OGS_C.NONE_STR

    normalized = value.replace(OGS_C.SPACE_STR, OGS_C.ZERO_STR)
    degrees, minutes = normalized.split(OGS_C.DASH_STR)
    return float(degrees) + float(minutes) / 60.

  @staticmethod
  def _parse_optional_int(value: str):
    """Convert an optional integer field, preserving empty values as NONE."""
    if not value:
      return OGS_C.NONE_STR
    return int(value.replace(OGS_C.SPACE_STR, OGS_C.ZERO_STR))

  @staticmethod
  def _parse_zero_padded_float(value: str) -> float:
    """Convert a numeric field, mapping placeholder-only values to NaN."""
    normalized = value.strip()
    if not any(character.isdigit() for character in normalized):
      return float("nan")
    return float(normalized.replace(OGS_C.SPACE_STR, OGS_C.ZERO_STR))

  def read(self):
    """
    Read and parse a .pun format file into an event summary DataFrame.

    The parser skips the header line, extracts one event summary per remaining
    line, filters by the configured date range, and stores grouped results in
    self.EVENTS and self.events.

    Raises:
      FileNotFoundError: If the input file does not exist.
      ValueError: If the input file does not use the .pun extension.
    """
    # -----------------------------------------------------------------------
    # INPUT VALIDATION
    # -----------------------------------------------------------------------
    if not self.input.exists():
      raise FileNotFoundError(f"File {self.input} does not exist")

    if self.input.suffix != OGS_C.PUN_EXT:
      raise ValueError(f"File extension must be {OGS_C.PUN_EXT}")

    # -----------------------------------------------------------------------
    # FILE READING
    # -----------------------------------------------------------------------
    events_data = list()
    event_counter = 0

    # The first line is a header banner and does not contain event data.
    with open(self.input, 'r') as fr:
      lines = fr.readlines()[1:]
    self.logger.info(f"Reading PUN file: {self.input}")

    # -----------------------------------------------------------------------
    # LINE-BY-LINE PARSING
    # -----------------------------------------------------------------------
    for line in [raw_line.strip() for raw_line in lines]:
      match = self.RECORD_EXTRACTOR.match(line)

      if not match:
        self.logger.error(f"(PUN) Could not parse line: {line}")
        self.debug(line, self.RECORD_EXTRACTOR_LIST)
        continue

      result: dict = match.groupdict()

      # ---------------------------------------------------------------------
      # DATE PROCESSING AND RANGE FILTERING
      # ---------------------------------------------------------------------
      result[OGS_C.SECONDS_STR] = self._parse_seconds(result[OGS_C.SECONDS_STR])
      result[OGS_C.DATE_STR] = self._parse_origin_time(
        result[OGS_C.DATE_STR], result[OGS_C.SECONDS_STR])

      if self.start is not None and result[OGS_C.DATE_STR] < self.start:
        self.logger.debug(f"Skipping event before start date: {self.start}")
        self.logger.debug(line)
        continue

      if (self.end is not None and
          result[OGS_C.DATE_STR] >= self.end + OGS_C.ONE_DAY):
        self.logger.debug(f"Stopping read at event after end date: {self.end}")
        self.logger.debug(line)
        break

      # ---------------------------------------------------------------------
      # FIELD PROCESSING
      # ---------------------------------------------------------------------
      result[OGS_C.LATITUDE_STR] = self._parse_coordinate(
        result[OGS_C.LATITUDE_STR])
      result[OGS_C.LONGITUDE_STR] = self._parse_coordinate(
        result[OGS_C.LONGITUDE_STR])
      result[OGS_C.DEPTH_STR] = float(result[OGS_C.DEPTH_STR]) \
        if result[OGS_C.DEPTH_STR] else OGS_C.NONE_STR
      result[OGS_C.NO_STR] = self._parse_optional_int(result[OGS_C.NO_STR])
      result[OGS_C.GAP_STR] = int(result[OGS_C.GAP_STR].replace(
        OGS_C.SPACE_STR, OGS_C.ZERO_STR))
      result[OGS_C.DMIN_STR] = self._parse_zero_padded_float(
        result[OGS_C.DMIN_STR])
      result[OGS_C.RMS_STR] = self._parse_zero_padded_float(
        result[OGS_C.RMS_STR])
      result[OGS_C.ERH_STR] = self._parse_zero_padded_float(
        result[OGS_C.ERH_STR])
      result[OGS_C.ERZ_STR] = self._parse_zero_padded_float(
        result[OGS_C.ERZ_STR])

      # ---------------------------------------------------------------------
      # APPEND EVENT SUMMARY TO RESULTS
      # ---------------------------------------------------------------------
      events_data.append([
        event_counter + result[OGS_C.DATE_STR].year * OGS_C.MAX_PICKS_YEAR,
        result[OGS_C.DATE_STR],
        result[OGS_C.LATITUDE_STR],
        result[OGS_C.LONGITUDE_STR],
        result[OGS_C.DEPTH_STR],
        result[OGS_C.MAGNITUDE_D_STR],
        result[OGS_C.NO_STR],
        result[OGS_C.GAP_STR],
        result[OGS_C.DMIN_STR],
        result[OGS_C.RMS_STR],
        result[OGS_C.ERH_STR],
        result[OGS_C.ERZ_STR],
        result[OGS_C.QM_STR],
        None,
        result[OGS_C.DATE_STR].strftime(OGS_C.DATE_FMT),
      ])
      event_counter += 1

    # -----------------------------------------------------------------------
    # BUILD OUTPUT DATAFRAME
    # -----------------------------------------------------------------------
    self.EVENTS = pd.DataFrame(events_data, columns=[
      OGS_C.INDEX_STR, OGS_C.TIME_STR, OGS_C.LATITUDE_STR,
      OGS_C.LONGITUDE_STR, OGS_C.DEPTH_STR, OGS_C.MAGNITUDE_D_STR,
      OGS_C.NO_STR, OGS_C.GAP_STR, OGS_C.DMIN_STR, OGS_C.RMS_STR,
      OGS_C.ERH_STR, OGS_C.ERZ_STR, OGS_C.QM_STR, OGS_C.NOTES_STR,
      OGS_C.GROUPS_STR
    ]).astype({OGS_C.INDEX_STR: int})

    self.EVENTS[OGS_C.MAGNITUDE_D_STR] = self.EVENTS[
      OGS_C.MAGNITUDE_D_STR
    ].replace(OGS_C.SPACE_STR * 5, "NaN").apply(float)

    self.logger.info(f"Total events read: {len(self.EVENTS)}")

    for date, dataframe in self.EVENTS.groupby(OGS_C.GROUPS_STR):
      self.events[UTCDateTime(date).date] = dataframe


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main(args):
  """
  Main entry point for command-line execution.

  Processes each input file specified on the command line:
    1. Creates a DataFilePUN parser instance
    2. Reads and parses the file
    3. Logs output through the shared OGS pipeline

  Args:
    args: Parsed command-line arguments from parse_arguments()
  """
  for file in args.file:
    datafile = DataFilePUN(file, args.dates[0], args.dates[1],
                           verbose=args.verbose)
    datafile.read()
    datafile.log()


if __name__ == "__main__":
  main(parse_arguments())