"""
===============================================================================
OGS PUN File Parser - Hypo71 Event Summary Extractor
===============================================================================

OVERVIEW:
This module parses OGS .pun format files containing event-level summaries
generated by legacy Hypo71 location workflows. PUN files store one summary
record per event, including origin time, hypocenter, magnitude, and quality
metrics.

FILE FORMAT DESCRIPTION:
  The .pun format uses one fixed-width record per event with fields for:
  - Origin date/time (YYMMDDHHMM plus seconds)
  - Latitude and longitude in degree-minute notation
  - Depth and duration magnitude
  - Number of observations, GAP, DMIN, RMS, ERH, ERZ, and QM quality code
  - The first line is unconditionally skipped as a header
  - Data regex matches a prefix beginning with "1"; suffix text is accepted

KEY FEATURES:
  - Regex-based extraction with named capture groups
  - Date range filtering for temporal subsetting
  - Conversion of degree-minute coordinates to decimal degrees
  - Preservation of event quality metrics for downstream analysis
  - Parquet output via the shared OGSDataFile logging pipeline

USAGE:
  Command line:
    python -m OGS.src.ogspun -f input.pun -D 20240320 20240620 -v

  Programmatic:
    from pathlib import Path
    from OGS.src.ogspun import DataFilePUN
    parser = DataFilePUN(Path("input.pun"), start_date, end_date)
    parser.read()
    parser.log()

OUTPUT:
  - self.EVENTS: DataFrame with event origin, geometry, and quality metrics
  - self.events: Dict mapping dates to grouped event DataFrames

DEPENDENCIES:
  - pandas: DataFrame operations and Parquet I/O
  - obspy: UTCDateTime for seismological time handling
  - ogsconstants: OGS-specific constants and regex fragments
  - ogsdatafile: Base class providing regex extraction and logging helpers

AUTHORS:
  - 健
  - Istituto Nazionale di Oceanografia e di Geofisica Sperimentale (OGS)
    Centro di Ricerche Sismologiche (CRS)
  - Università degli Studi di Trieste (UniTS)
    Dipartimento di Matematica, Informatica e Geoscienze (MIGe)
    Applied Data Science and Artificial Intelligence (ADSAI)
  - Terabit Network for Research and Academic Big Data in Italy (TeRABIT)
    Consorzio Interuniversitario del Nord-Est per il Calcolo Automatico (CINECA)

===============================================================================
"""

# -----------------------------------------------------------------------------
# IMPORTS
# -----------------------------------------------------------------------------

# Standard library: date/time objects and time deltas
from datetime import datetime, timedelta as td

from . import ogsconstants as OGS_C, ogsutils as OGS_U
from .ogsdatafile import OGSDataFile


# =============================================================================
# DataFilePUN Class - PUN Format Parser
# =============================================================================

class DataFilePUN(OGSDataFile):
  """
  Parser for OGS .pun format event summary files.

  Extends OGSDataFile to parse legacy Hypo71 event summary output. Each data
  line represents one event and includes origin time, hypocenter, and several
  quality-control metrics used by downstream catalog workflows.

  Attributes:
    EVENT_EXTRACTOR_LIST: Regex patterns for event summary lines
  """

  # Expected file extension for format validation
  EXTENSION: str = OGS_C.PUN_EXT

  # PUN format contains event hypocenters only, no pick records
  HAS_PICKS: bool = False

  # -------------------------------------------------------------------------
  # EVENT EXTRACTOR: fixed-width event summary line
  # -------------------------------------------------------------------------
  EVENT_EXTRACTOR_LIST = [
      # Date [YYMMDDHHMM]
      fr"^1(?P<{OGS_C.DATE_STR}>\d{{6}}[\s\d]\d[\s\d]\d)\s",
      # Seconds [SS.ss]
      fr"(?P<{OGS_C.SECONDS_STR}>[\s\d]\d\.\d{{2}})\s",
      # Latitude [DD-MM.mm]
      fr"(?P<{OGS_C.LATITUDE_STR}>[\s\d\-\.]{{8}})\s{{2}}",
      # Longitude [DD-MM.mm]
      fr"(?P<{OGS_C.LONGITUDE_STR}>[\s\d\-\.]{{8}})\s{{2}}",
      # Depth
      fr"(?P<{OGS_C.DEPTH_STR}>[\s\d\-\.]{{5}})\s{{2}}",
      # Duration Magnitude
      fr"(?P<{OGS_C.MAGNITUDE_D_STR}>[\-\s\d\.]{{5}})",
      # Number of Observations [DDD]
      fr"(?P<{OGS_C.NO_STR}>[\s\d]{{3}})\s",
      # GAP [DDD]
      fr"(?P<{OGS_C.GAP_STR}>[\s\d]{{3}})",
      # DMIN [DDD.D]
      fr"(?P<{OGS_C.DMIN_STR}>[\s\d]{{2}}\d\.\d)",
      # RMS [DD.DD]
      fr"(?P<{OGS_C.RMS_STR}>[\s\d]\d\.\d{{2}})",
      # ERH
      fr"(?P<{OGS_C.ERH_STR}>([\s\d\.\-\*]{{5}}))",
      # ERZ
      fr"(?P<{OGS_C.ERZ_STR}>([\s\d\.\-\*]{{5}}))\s",
      # Quality Metric [A-Z][0-9]
      fr"(?P<{OGS_C.QM_STR}>[A-Z][0-9])",
  ]

  @staticmethod
  def _parse_event_datetime(date_value: str, seconds: td) -> datetime:
    """Convert the origin date and seconds fields into a datetime."""
    return datetime.strptime(
        date_value.replace(OGS_C.SPACE_STR, OGS_C.ZERO_STR),
        OGS_C.DATETIME_FMT[:-2]
    ) + seconds

  def read(self):
    """
    Read and parse a .pun format file into an event summary DataFrame.

    The parser skips the header line, extracts one event summary per remaining
    line, filters by the configured date range, and stores grouped results in
    self.EVENTS and self.events. Reading stops at the first parsed event
    beyond the upper date bound, assuming chronological input. Event IDs use
    a zero-based counter of retained events plus the calendar-year stride,
    not an identifier read from the file.

    Returns:
      None: Results are stored on the instance.

    Raises:
      FileNotFoundError: If the input file does not exist.
      ValueError: If the suffix is not .pun or a field conversion fails.
      OSError: If opening or reading the file fails.
      UnicodeError: If UTF-8 decoding fails.
      Other processing failures propagate; regex mismatches are logged and
      skipped.
    """
    # -----------------------------------------------------------------------
    # INPUT VALIDATION
    # -----------------------------------------------------------------------
    self.validate_input()

    # -----------------------------------------------------------------------
    # FILE READING
    # -----------------------------------------------------------------------
    events_data: list[dict[str, object]] = []
    event_counter = 0

    self.logger.info(f"Reading PUN file: {self.input}")

    # -----------------------------------------------------------------------
    # LINE-BY-LINE PARSING
    # -----------------------------------------------------------------------
    with open(self.input, 'r', encoding='utf-8') as fr:
      next(fr, None)  # Skip header banner line lazily
      for raw_line in fr:
        line = raw_line.strip()
        if not line:
          continue

        match = self.EVENT_EXTRACTOR.match(line)
        if not match:
          self.logger.error(f"(PUN) Could not parse line: {line}")
          self.debug(line, self.EVENT_EXTRACTOR_LIST)
          continue

        result: dict = match.groupdict()

        # ---------------------------------------------------------------------
        # DATE PROCESSING AND RANGE FILTERING
        # ---------------------------------------------------------------------
        result[OGS_C.SECONDS_STR] = self._parse_seconds(
            result[OGS_C.SECONDS_STR]
        )
        result[OGS_C.DATE_STR] = self._parse_event_datetime(
            result[OGS_C.DATE_STR], result[OGS_C.SECONDS_STR]
        )

        if self._is_before_start(result[OGS_C.DATE_STR]):
          self.logger.debug(f"Skipping event before start date: {self.start}")
          self.logger.debug(line)
          continue

        if self._is_after_end(result[OGS_C.DATE_STR]):
          self.logger.debug(
              f"Stopping read at event after end date: {self.end}"
          )
          self.logger.debug(line)
          break

        # ---------------------------------------------------------------------
        # FIELD PROCESSING
        # ---------------------------------------------------------------------
        result[OGS_C.NO_STR] = self._parse_int(result[OGS_C.NO_STR])
        result[OGS_C.GAP_STR] = self._parse_int(result[OGS_C.GAP_STR])
        result[OGS_C.DMIN_STR] = self._parse_float(result[OGS_C.DMIN_STR])
        result[OGS_C.RMS_STR] = self._parse_float(result[OGS_C.RMS_STR])
        result[OGS_C.ERH_STR] = self._parse_float(result[OGS_C.ERH_STR])
        result[OGS_C.ERZ_STR] = self._parse_float(result[OGS_C.ERZ_STR])
        result[OGS_C.IDX_EVENTS_STR] = self.normalize_index(
            event_counter, result[OGS_C.DATE_STR].year
        )
        result[OGS_C.TIME_STR] = result[OGS_C.DATE_STR]
        events_data.append(result)
        event_counter += 1

    # -----------------------------------------------------------------------
    # BUILD OUTPUT DATAFRAME
    # -----------------------------------------------------------------------
    self.EVENTS = self._build_events_dataframe(events_data)
    self.logger.info(f"Total events read: {len(self.EVENTS)}")
    self.postload("events", update=True)


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main(args):
  """
  Main entry point for command-line execution.

  Processes each input file specified on the command line:
    1. Creates a DataFilePUN parser instance
    2. Reads and parses the file
    3. Logs output through the shared OGS pipeline

  Args:
    args: Parsed command-line arguments from ogsutils.parse_pun_args()
  """
  for file in args.file:
    datafile = DataFilePUN(
        file, args.dates[0], args.dates[1], verbose=args.verbose
    )
    datafile.read()
    datafile.log()


if __name__ == "__main__":
  main(OGS_U.parse_pun_args())
