all: .dat .hpl .pun .txt parser constants

constants:
	python testogsconstants.py

parser:
	python testogsparser.py

.dat:
	python testogsdat.py

.hpl:
	python testogshpl.py

.pun:
	python testogspun.py

.txt:
	python testogstxt.py