all: .dat .hpl .pun .txt parser constants clustering downloader catalog data

constants:
	python testogsconstants.py

parser:
	python testogsparser.py

.dat:
	python testogsdat.py

.hpl:
	python testogshpl.py

.pun:
	python testogspun.py

.txt:
	python testogstxt.py
clustering:
	python testogsclustering.py

downloader:
	python testogsdownloader.py

catalog:
	python testogscatalog.py

data:
	python testogsdata.py
